
name: Github 同步到 Gitee
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  #pull_request:
   # branches: [ main ]
  #schedule:
    #- cron: '30 0/3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run:
    name: 把该仓库同步到 Gitee（使用白名单只同步这个仓库）
    runs-on: ubuntu-latest
    steps:

    # - name: Mirror Github to Gitee with white list
    #   uses: Yikun/hub-mirror-action@master
    #   with:
    #     src: github/nmydt
    #     dst: gitee/nmydt
    #     dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    #     dst_token:  ${{ secrets.GITEE_TOKEN }}
    #     mappings: "nmydt.github.io=>nmydt"
    #     static_list: "nmydt.github.io"
    #     force_update: true
    #     debug: true
    - name: Mirror Github to Gitee with white list
      env:
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      run: |
        git config --global user.email 319485106@qq.com
        git config --global user.name nmydt
        git clone https://github.com/nmydt/project.git
        
        cd project
        ls -al
        rm -rf .github
        pwd
        find . -type f | xargs sed -i "s/lylg102/192.168.10.112/g"  
        find . -type f | xargs sed -i "s/000000/123456/g"  
        git add .
        git commit -m "update" 
           
        git push --force --quiet https://nmydt:"$GITEE_TOKEN"@gitee.com/nmydt/project.git  master:master
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
        # 注意替换为你的 Gitee 用户名
        gitee-username: nmydt
        # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
        gitee-repo: project
        # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
        branch: master
#     - name: Single repo mirror
#       uses: Yikun/hub-mirror-action@master
#       with:
#         src: github/nmydt
#         dst: gitee/nmydt
#         dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#         dst_token:  ${{ secrets.GITEE_TOKEN }}
#         white_list: "project"
#         force_update: true
